Playgourd for the "Regression forecasting and predicting.ipynb"

In [21]:
import numpy as np

In [22]:
import pandas as pd2

df2 = pd2.DataFrame({'x1': ['206', '226', '245',' 265', '283'],
                    'x2': ['214', '234', '253', '272', '291']})

df2['label'] = df2['x2'].shift(-2) #create a label columns and shift 2 rows from bottom
df2.fillna(-99999, inplace=True)
df2['label2'] = df2['x2'].shift(-2) #create for experiment
print(df2)


#print(df2)

     x1   x2   label label2
0   206  214     253    253
1   226  234     272    272
2   245  253     291    291
3   265  272  -99999    NaN
4   283  291  -99999    NaN


In [23]:
X = np.array(df2.drop(['label2'],1))
print (X)
#X = X[:-forecast_out]
#X_lately = X[-forecast_out:]
#X = preprocessing.scale(X)

#df.dropna(inplace=True)
#y = np.array(df['label'])
#y = np.array(df['label'])

#print(len(X),len(y))

[['206' '214' '253']
 ['226' '234' '272']
 ['245' '253' '291']
 [' 265' '272' -99999]
 ['283' '291' -99999]]


In [24]:
X = preprocessing.scale(X)
X = X[:-2]
print (X)

[[-1.42865769 -1.42886743  0.81610977]
 [-0.69601272 -0.69233783  0.81649656]
 [ 0.          0.0073653   0.81688334]]


/home/jia/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


In [25]:
X_lately = X[-2:]
print (X_lately)

[[-0.69601272 -0.69233783  0.81649656]
 [ 0.          0.0073653   0.81688334]]


In [26]:
from sklearn import preprocessing, svm


In [27]:
print (X)

[[-1.42865769 -1.42886743  0.81610977]
 [-0.69601272 -0.69233783  0.81649656]
 [ 0.          0.0073653   0.81688334]]


In [28]:
df2.dropna(inplace=True)
y = np.array(df2['label2'])
print (y)

['253' '272' '291']


In [29]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
#clf = LinearRegression(n_jobs=-1)
#clf = svm.SVR(kernel='poly')
#clf.fit(X_train, y_train)
#ccuracy = clf.score(X_test, y_test)

#print(accuracy)
print (X_train)
print (X_test)
print (y_train)
print (y_test)

[[ 0.          0.0073653   0.81688334]
 [-0.69601272 -0.69233783  0.81649656]]
[[-1.42865769 -1.42886743  0.81610977]]
['291' '272']
['253']


In [31]:
clf = LinearRegression(n_jobs=-1)
#clf = svm.SVR(kernel='poly')
clf.fit(X_train, y_train)
accuracy = clf.score(X_test, y_test)

print(accuracy)

0.0
