## 2. [Introduction to NumPy](https://github.com/jakevdp/PythonDataScienceHandbook)
* Understanding Data Types in Python
* The Basics of NumPy Arrays
* Computation on NumPy Arrays: Universal Functions
* Aggregations: Min, Max, and Everything In Between
* Computation on Arrays: Broadcasting
* Comparisons, Masks, and Boolean Logic
* Fancy Indexing
* Sorting Arrays
* Structured Data: NumPy's Structured Arrays

In [43]:
import numpy
numpy.__version__

'1.15.4'

In [44]:
import array
L = list(range(10))
A = array.array('i', L) #Here 'i' is a type code indicating the contents are integers
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
import numpy as np

In [46]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [47]:
# np.array same type, here, integers are up-cast to floating point
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [48]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [49]:
# nested lists result in multi-dimensional arrays
x15 = [range(i, i + 3) for i in [2, 4, 6]]
print(x15)
np.array(x15)

[range(2, 5), range(4, 7), range(6, 9)]


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [50]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
np.full((5,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [93]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [54]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [55]:
np.random.random((3, 3))

array([[0.62334841, 0.14444406, 0.51207485],
       [0.69334496, 0.67669169, 0.59289878],
       [0.91060535, 0.82007609, 0.7621873 ]])

In [56]:
np.random.randint(0, 100, (5,5))

array([[79, 35, 10, 46, 52],
       [45, 30, 46, 23, 67],
       [59, 41, 34,  8, 79],
       [38, 27, 99, 13,  3],
       [69,  8, 46, 89, 51]])

In [57]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

#####NumPy Standard Data Types

| Data type|Description |
|:---|:------------ |
|bool_	| Boolean (True or False) stored as a byte |
|int_	| Default integer type (same as C long; normally either int64 or int32)|
|intc	| Identical to C int (normally int32 or int64)|
|intp	| Integer used for indexing (same as C ssize_t; normally either int32 or int64)|
|int8	| Byte (-128 to 127)|
|int16	| Integer (-32768 to 32767)|
|int32	| Integer (-2147483648 to 2147483647)|
|int64	|Integer (-9223372036854775808 to 9223372036854775807)|
|uint8	|Unsigned integer (0 to 255)|
|uint16	|Unsigned integer (0 to 65535)|
|uint32	|Unsigned integer (0 to 4294967295)|
|uint64	|Unsigned integer (0 to 18446744073709551615)|
|float_	|Shorthand for float64.|
|float16	|Half precision float: sign bit, 5 bits exponent, 10 bits mantissa|
|float32	|Single precision float: sign bit, 8 bits exponent, 23 bits mantissa|
|float64	|Double precision float: sign bit, 11 bits exponent, 52 bits mantissa|
|complex_ |	Shorthand for complex128.|
|complex64	| Complex number, represented by two 32-bit floats|
|complex128	| Complex number, represented by two 64-bit floats|

## The Basics of NumPy Arrays

In [67]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print(x3)
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

[[[0 7 5 0 5]
  [8 3 0 0 0]
  [4 9 6 4 5]
  [5 3 8 6 2]]

 [[5 5 1 2 8]
  [5 0 4 5 1]
  [4 9 0 9 3]
  [7 0 9 8 8]]

 [[6 6 4 4 5]
  [0 2 8 1 3]
  [6 5 1 2 5]
  [6 5 0 4 0]]]
x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


In [69]:
x1

array([9, 3, 3, 6, 4, 6])

In [71]:
x1[::2]  # every other element

array([9, 3, 4])

In [72]:
x1[1::2]  # every other element, starting at index 1

array([3, 6, 6])

In [73]:
x1[::-1]  # all elements, reversed

array([6, 4, 6, 3, 3, 9])

In [74]:
x1[5::-2]  # reversed every other from index 5

array([6, 6, 3])

In [76]:
x2

array([[5, 5, 9, 9],
       [9, 2, 9, 6],
       [7, 3, 0, 0]])

In [77]:
x2[:2, :3]  # two rows, three columns

array([[5, 5, 9],
       [9, 2, 9]])

In [78]:
x2[:3, ::2]  # all rows, every other column

array([[5, 9],
       [9, 9],
       [7, 0]])

In [79]:
x2[::-1, ::-1]

array([[0, 0, 3, 7],
       [6, 9, 2, 9],
       [9, 9, 5, 5]])

In [80]:
print(x2[:, 0])  # first column of x2

[5 9 7]


In [81]:
print(x2[0, :])  # first row of x2

[5 5 9 9]


In [84]:
print(x2[0])  # equivalent to x2[0, :]

[5 5 9 9]


In [85]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[5 5]
 [9 2]]


In [86]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 9  2]]


In [88]:
print(x2)

[[5 5 9 9]
 [9 2 9 6]
 [7 3 0 0]]


In [94]:
grid = np.arange(1,10).reshape(3,3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
x95 = np.array([1, 2, 3])

# row vector via reshape
x95.reshape((1, 3))

array([[1, 2, 3]])

In [96]:
# row vector via newaxis
x95[np.newaxis, :]

array([[1, 2, 3]])

In [98]:
# column vector via reshape
x95.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [99]:
# column vector via newaxis
x95[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [100]:
np.split?